// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
)

type Todo struct {
	Name string
	ID   uuid.UUID
	Done bool
	Pk   int32
	Pos  int32
}
